name: 'Dependency Generation CSV'
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Generate Dependencies Action'
        uses: thedave42/generate-dependencies-csv-action@84e22e5810d308a8ce71793e253f6a12378c8a00
        with:
          repo-token: ${{ secrets.DEP_GITHUB_TOKEN }}
          org-name: customer-success-architects
          depth: 0
          repo-names: angular
